ledger:
  networks: "mainnet=grpc.cheqd.net:443;testnet=grpc.cheqd.network:443"
  useTls: true
  timeout: "5s"

resolver:
  method: "cheqd"

api:
  listener: "0.0.0.0:8080"
  resolverPath: "/1.0/identifiers/"

logLevel: "trace"
